import "./globals.css";
import { Poppins } from "next/font/google";

import { ContextProvider } from "./context/contextProvider";
import { ReactNode } from "react";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>{children} </ContextProvider>
      </body>
    </html>
  );
}
